services:
  - type: web
    name: intelliface
    env: python
    buildCommand: "pip install -r requirements-railway.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn IntelliFace.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: intelliface-db
          property: connectionString

databases:
  - name: intelliface-db
    databaseName: intelliface
    user: intelliface